theme_name: Ronin Simple Theme
author: Benjamin
css: /css/style.css

logo: /images/default-logo.svg
favicon:
profile_picture: /images/default-profile-picture.jpg
author_description: 作者簡介
copyright_year: 2025
contact_link:
contact_mail:
google_analytics:
